type: object
required:
  - foo
properties:
  arr:
    type: array
    items:
      type: integer
  foo:
    type: object
    properties:
      bar:
        type: integer
      baz:
        type: integer
      qux:
        type: integer
